# -*- coding: utf-8 -*-
"""day1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12esLYq8lc9H9ZK1Udmh99wN-rW4kS0gi

variables
"""

a = 1 
b = 2
print ("a","b")

"""Python Local Variables are defined inside a function. We can not access variable outside the function."""

def sum(x,y):
   sum = x + y
   return sum
print(sum(4, 1))